steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  id: Deploy API
  args: ['run', 'deploy', 'service-bags',
             '--source=.',
             '--service-account=langgraph-agent-sa@langgraph-422507.iam.gserviceaccount.com',
             '--region=me-west1',
              '--allow-unauthenticated',
              '--min-instances=1']