from pinecone_text.sparse import BM25Encoder

corpus = [
    "beige classic 2",
    "beige classic 4",
    "beige classic cymbal cymbal 5",
    "beige classic cymbal 1",
    "beige classic cymbal 3",
    "beige fantasy 2",
    "beige fantasy 4",
    "beige fantasy cymbal 1",
    "beige fantasy cymbal 3",
    "black channel-like 2",
    "black channel-like 4",
    "black channel-like cymbal 1",
    "black channel-like cymbal 3",
    "black classic 2",
    "black classic 4",
    "black classic cymbal 1",
    "black classic cymbal 3",
    "black quilted 1",
    "black quilted 2",
    "black quilted 3",
    "black quilted 4",
    "black quilted studs 2",
    "black quilted studs 3",
    "black quilted studs 4",
    "black quilted studs cymbal cymbal 1",
    "burberry 2",
    "burberry 4",
    "burberry cymbal 1",
    "burberry cymbal 3",
    "chanel-like 2",
    "chanel-like 4",
    "chanel-like cymbal 1",
    "chanel-like cymbal 3",
    "classic 2",
    "classic 4",
    "classic cymbal 1",
    "classic cymbal 3",
    "green classic 2",
    "green classic 4",
    "green classic cymbal 1",
    "green classic cymbal 3",
    "green modern 2",
    "green modern 4",
    "green modern cymbal 1",
    "green modern cymbal 3",
    "leopard classic 2",
    "leopard classic 4",
    "leopard classic cymbal 1",
    "leopard classic cymbal 3",
    "marine classic 2",
    "marine classic 4",
    "marine classic cymbal 1",
    "marine classic cymbal 3",
    "orange classic 2",
    "orange classic 4",
    "orange classic cymbal 1",
    "orange classic cymbal 3",
    "orange fantasy 2",
    "orange fantasy 4",
    "orange fantasy cymbal 1",
    "orange fantasy cymbal 3",
    "red 2",
    "red 4",
    "red cymbal 1",
    "red cymbal 3",
    "red modern 2",
    "red modern 4",
    "red modern cymbal 1",
    "red modern cymbal 3",
    "red old school 2",
    "red old school 4",
    "red old school cymbal 1",
    "red old school cymbal 3",
    "sea colorful 2",
    "sea colorful 4",
    "sea colorful cymbal 1",
    "sea colorful cymbal 3",
    "sea cute  2",
    "sea cute  4",
    "sea cute  cymbal 1",
    "sea cute  cymbal 3",
    "sea cute 5",
    "sea cute 6",
    "sea cute 7",
    "sea cute 8",
    "sea esthetic 2",
    "sea esthetic 4",
    "sea esthetic 5",
    "sea esthetic cymbal 1",
    "sea esthetic cymbal 3",
    "sea kitten  2",
    "sea kitten  4",
    "sea kitten  cymbal 1",
    "sea kitten  cymbal 3",
    "yellow classic 2",
    "yellow classic 4",
    "yellow classic cymbal 1",
    "yellow classic cymbal 3",
    "yellow old school 2",
    "yellow old school 4",
    "yellow old school cymbal 1",
    "yellow old school cymbal 3",
]

bm25 = BM25Encoder()
bm25.fit(corpus)
